// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bmiCalculator.Data;

#nullable disable

namespace bmiCalculator.Migrations
{
    [DbContext(typeof(BmiDbContext))]
    partial class BmiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("bmiCalculator.Models.BmiResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Bmi")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<double>("Height")
                        .HasColumnType("double");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("bmi_results", (string)null);
                });

            modelBuilder.Entity("bmiCalculator.Models.LocalizationString", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("localization_strings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "title",
                            Language = "en",
                            Value = "BMI Calculator"
                        },
                        new
                        {
                            Id = 2,
                            Key = "weight_label",
                            Language = "en",
                            Value = "Weight (kg)"
                        },
                        new
                        {
                            Id = 3,
                            Key = "height_label",
                            Language = "en",
                            Value = "Height (cm)"
                        },
                        new
                        {
                            Id = 4,
                            Key = "calculate_button",
                            Language = "en",
                            Value = "Calculate BMI"
                        },
                        new
                        {
                            Id = 5,
                            Key = "result_title",
                            Language = "en",
                            Value = "Your BMI Result"
                        },
                        new
                        {
                            Id = 6,
                            Key = "category_label",
                            Language = "en",
                            Value = "Category"
                        },
                        new
                        {
                            Id = 7,
                            Key = "underweight",
                            Language = "en",
                            Value = "Underweight"
                        },
                        new
                        {
                            Id = 8,
                            Key = "normal_weight",
                            Language = "en",
                            Value = "Normal weight"
                        },
                        new
                        {
                            Id = 9,
                            Key = "overweight",
                            Language = "en",
                            Value = "Overweight"
                        },
                        new
                        {
                            Id = 10,
                            Key = "obese",
                            Language = "en",
                            Value = "Obese"
                        },
                        new
                        {
                            Id = 11,
                            Key = "weight_placeholder",
                            Language = "en",
                            Value = "Enter your weight in kilograms"
                        },
                        new
                        {
                            Id = 12,
                            Key = "height_placeholder",
                            Language = "en",
                            Value = "Enter your height in centimeters"
                        },
                        new
                        {
                            Id = 13,
                            Key = "title",
                            Language = "fi",
                            Value = "BMI Laskin"
                        },
                        new
                        {
                            Id = 14,
                            Key = "weight_label",
                            Language = "fi",
                            Value = "Paino (kg)"
                        },
                        new
                        {
                            Id = 15,
                            Key = "height_label",
                            Language = "fi",
                            Value = "Pituus (cm)"
                        },
                        new
                        {
                            Id = 16,
                            Key = "calculate_button",
                            Language = "fi",
                            Value = "Laske BMI"
                        },
                        new
                        {
                            Id = 17,
                            Key = "result_title",
                            Language = "fi",
                            Value = "BMI Tuloksesi"
                        },
                        new
                        {
                            Id = 18,
                            Key = "category_label",
                            Language = "fi",
                            Value = "Kategoria"
                        },
                        new
                        {
                            Id = 19,
                            Key = "underweight",
                            Language = "fi",
                            Value = "Alipaino"
                        },
                        new
                        {
                            Id = 20,
                            Key = "normal_weight",
                            Language = "fi",
                            Value = "Normaali paino"
                        },
                        new
                        {
                            Id = 21,
                            Key = "overweight",
                            Language = "fi",
                            Value = "Ylipaino"
                        },
                        new
                        {
                            Id = 22,
                            Key = "obese",
                            Language = "fi",
                            Value = "Lihava"
                        },
                        new
                        {
                            Id = 23,
                            Key = "weight_placeholder",
                            Language = "fi",
                            Value = "Syötä painosi kilogrammoina"
                        },
                        new
                        {
                            Id = 24,
                            Key = "height_placeholder",
                            Language = "fi",
                            Value = "Syötä pituutesi senttimetreinä"
                        },
                        new
                        {
                            Id = 25,
                            Key = "title",
                            Language = "fa",
                            Value = "محاسبه BMI"
                        },
                        new
                        {
                            Id = 26,
                            Key = "weight_label",
                            Language = "fa",
                            Value = "وزن (کیلوگرم)"
                        },
                        new
                        {
                            Id = 27,
                            Key = "height_label",
                            Language = "fa",
                            Value = "قد (سانتی‌متر)"
                        },
                        new
                        {
                            Id = 28,
                            Key = "calculate_button",
                            Language = "fa",
                            Value = "محاسبه BMI"
                        },
                        new
                        {
                            Id = 29,
                            Key = "result_title",
                            Language = "fa",
                            Value = "نتیجه BMI شما"
                        },
                        new
                        {
                            Id = 30,
                            Key = "category_label",
                            Language = "fa",
                            Value = "دسته‌بندی"
                        },
                        new
                        {
                            Id = 31,
                            Key = "underweight",
                            Language = "fa",
                            Value = "کم وزن"
                        },
                        new
                        {
                            Id = 32,
                            Key = "normal_weight",
                            Language = "fa",
                            Value = "وزن طبیعی"
                        },
                        new
                        {
                            Id = 33,
                            Key = "overweight",
                            Language = "fa",
                            Value = "اضافه وزن"
                        },
                        new
                        {
                            Id = 34,
                            Key = "obese",
                            Language = "fa",
                            Value = "چاق"
                        },
                        new
                        {
                            Id = 35,
                            Key = "weight_placeholder",
                            Language = "fa",
                            Value = "وزن خود را به کیلوگرم وارد کنید"
                        },
                        new
                        {
                            Id = 36,
                            Key = "height_placeholder",
                            Language = "fa",
                            Value = "قد خود را به سانتی‌متر وارد کنید"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
